Script started on 2017年03月16日 (週四) 11時19分20秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./[K[Kls
lab1.cpp  lab1.script  Q2.script  [0m[01;32mquestion2[0m
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./lab1.cpp
bash: ./lab1.cpp: Permission denied
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m ./questu[Ko[Kion2
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/lab1 $[00m exit
exit

Script done on 2017年03月16日 (週四) 11時20分28秒
